"""empty message

Revision ID: 2bcf0967d5c0
Revises: d5e8b1fc69bb
Create Date: 2022-01-19 15:33:06.732549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bcf0967d5c0'
down_revision = 'd5e8b1fc69bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
