"""add createdAt to User

Revision ID: 7e73faf6751a
Revises: 2bcf0967d5c0
Create Date: 2022-01-19 15:34:12.114963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e73faf6751a'
down_revision = '2bcf0967d5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createdAt')
    # ### end Alembic commands ###
