"""createdAt not-null

Revision ID: 91d2af5f5504
Revises: 7e73faf6751a
Create Date: 2022-01-19 15:35:46.345840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91d2af5f5504'
down_revision = '7e73faf6751a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
